[[QhullMiniWrapper]]
arch = "aarch64"
git-tree-sha1 = "1ebd23c7f5883db82a911d2f849c7e012755ab45"
os = "macos"

    [[QhullMiniWrapper.download]]
    sha256 = "dd6369bc7810074937140cfe048ad68045cab1e389bed4f8b7d8fa6761d71b29"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.aarch64-apple-darwin.tar.gz"
[[QhullMiniWrapper]]
arch = "aarch64"
git-tree-sha1 = "cb33d64ca567ff5ee03922d4c39f1e6b55a5d4dd"
libc = "glibc"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "2b7ae496d876020d33702721fce5ccda214b8d668de6fa69291c9507cf334ea5"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.aarch64-linux-gnu.tar.gz"
[[QhullMiniWrapper]]
arch = "aarch64"
git-tree-sha1 = "4b7b794c3f6afda2f21061e378acb850138a9648"
libc = "musl"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "ef6fddaaddb8839af859b2fa042d5fd65896e0fc23a18dc962b21851bdc6f0d5"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.aarch64-linux-musl.tar.gz"
[[QhullMiniWrapper]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b42f2a27e5fc7ccdb61f2a0bbf33ca34cad001f9"
libc = "glibc"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "c6399758a343584ea70c72b533b06024396cd98b25cd13720900c3bc22b9e607"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[QhullMiniWrapper]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9336acff0f84f887b8a412d8091c582193a63466"
libc = "musl"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "d766c06f729828f7adbb0f2fa5c14329e835f50f0ee05b33537a6250fdb830e7"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[QhullMiniWrapper]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "10beb1e10d3317889ce7f457089043fc649fde50"
libc = "glibc"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "85825210b942d7588551aa6e7aa2c0e26cc6b2aac235dd4d4551a6c788f20a71"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[QhullMiniWrapper]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "542c4248f91f41f7f18cbf3e06a8ea02bfff771d"
libc = "musl"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "de2ed4462cdd741b5f7c86d45683d1d7788ec2263e28c3e0678cd0259be86b9e"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[QhullMiniWrapper]]
arch = "i686"
git-tree-sha1 = "0b3ab55f36722b1941202edd229d10d6cca6a945"
libc = "glibc"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "003a934e976835bd0db17c4ee42de6434e59defe314838569a9824fc20be5678"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.i686-linux-gnu.tar.gz"
[[QhullMiniWrapper]]
arch = "i686"
git-tree-sha1 = "02c05c1ba95746b0d8e7f5132b789b4f71c15391"
libc = "musl"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "d5a241e6c228814aa643eddbd3664e001dccc65b9f58069b9929610da2dfd026"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.i686-linux-musl.tar.gz"
[[QhullMiniWrapper]]
arch = "i686"
git-tree-sha1 = "b7077af84eba209ed850f4ad3218f26e2eeccaaf"
os = "windows"

    [[QhullMiniWrapper.download]]
    sha256 = "4527790769edc662e2f08ce50a9044727b55342fc1c85e00ca0aa26c949943b9"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.i686-w64-mingw32.tar.gz"
[[QhullMiniWrapper]]
arch = "powerpc64le"
git-tree-sha1 = "0461b550c079371f856df82cce55d6fe5e8b6ea6"
libc = "glibc"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "c42d86a128766aac0b1f11136e8f763a2e3686562054ce907b00ad8c5db8f044"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[QhullMiniWrapper]]
arch = "x86_64"
git-tree-sha1 = "005939a6f2e48e97260857ee9499958a98178a52"
os = "macos"

    [[QhullMiniWrapper.download]]
    sha256 = "90338084b031440502ad2fdb12b851b9ee2a7a091f3176468ecd804ff02d99e1"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.x86_64-apple-darwin.tar.gz"
[[QhullMiniWrapper]]
arch = "x86_64"
git-tree-sha1 = "87b5a10c1d6161bc22588bf1819e77d9fda163dc"
libc = "glibc"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "d12e9fa59cefcb1de8ede55e698c0a156565588c14f9c41f0ba2d1f2f198e446"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.x86_64-linux-gnu.tar.gz"
[[QhullMiniWrapper]]
arch = "x86_64"
git-tree-sha1 = "0f41a0baf018e9207e1187bb2d5c6b3c189017a5"
libc = "musl"
os = "linux"

    [[QhullMiniWrapper.download]]
    sha256 = "aa13966ef4b45f07c3e618b415a7a8c32a79ff233fdf3969bb1f4a54ec651952"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.x86_64-linux-musl.tar.gz"
[[QhullMiniWrapper]]
arch = "x86_64"
git-tree-sha1 = "d0d8436a9628b8cd70c53c38f95f2d9a99c0bd29"
os = "freebsd"

    [[QhullMiniWrapper.download]]
    sha256 = "3ef2a26c092d407b431a903b7d19dfb40fde5e065e12c27cf84804d84f9b2d7b"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[QhullMiniWrapper]]
arch = "x86_64"
git-tree-sha1 = "06530e0d295a7db68fc950fa0ea865ad9f6cb41c"
os = "windows"

    [[QhullMiniWrapper.download]]
    sha256 = "ab4be81e7b0a38f78afbefbfcf51c0adb90c5e3afcf6c6109c4e0662b3fb40af"
    url = "https://github.com/JuliaBinaryWrappers/QhullMiniWrapper_jll.jl/releases/download/QhullMiniWrapper-v1.0.0+1/QhullMiniWrapper.v1.0.0.x86_64-w64-mingw32.tar.gz"
