# Autogenerated wrapper script for QhullMiniWrapper_jll for i686-w64-mingw32
export qhullwrapper

using Qhull_jll
JLLWrappers.@generate_wrapper_header("QhullMiniWrapper")
JLLWrappers.@declare_library_product(qhullwrapper, "qhullwrapper.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qhull_jll)
    JLLWrappers.@init_library_product(
        qhullwrapper,
        "bin\\qhullwrapper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
